import { Inter } from "next/font/google";
import "./globals.css";
import MouseClickEffect from "@/components/MouseClickEffect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Milkyway",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} rotate-90 md:rotate-0`}>
        <MouseClickEffect />
        {children}
      </body>
    </html>
  );
}
